set /p version=<version.txt
ECHO.%INFO%工具箱版本为%version%%RESET%
ECHO.%INFO%更新日志：%RESET%
ECHO.%INFO%1.优化z10一键root%RESET%
ECHO.%INFO%2.修复了备份相册%RESET%
ECHO.%INFO%3.增加新功能9008唯一分区备份%RESET%
ECHO.%INFO%4.复活了更新功能，提升下载速度%RESET%
ECHO.%INFO%5.修复了7.1安装xp框架%RESET%
ECHO.%INFO%6.新增imoopatch%RESET%
ECHO.%INFO%7.删除了xtcpatch%RESET%
ECHO.%INFO%8.sysp和wcp2更新%RESET%
ECHO.%INFO%9.清除所有“小天才”字眼%RESET%
ECHO.%INFO%10.更新驱动检查%RESET%
ECHO.%INFO%11.恢复出厂设置支持更多机型%RESET%
ECHO.%INFO%12.innermodel对照表补全更多机型%RESET%
ECHO.%INFO%13.模块和应用资源优化%RESET%
ECHO.%INFO%14.z10已添加预装个人中心防崩%RESET%
ECHO.%INFO%15.重构9008端口获取%RESET%
ECHO.%INFO%16.优化修补boot速度%RESET%
ECHO.%INFO%17.新增无线调试%RESET%
ECHO.%INFO%18.全部适配新菜单%RESET%
ECHO.%INFO%19.修复刷入twrp%RESET%
ECHO.%INFO%20.修复恢复出厂设置%RESET%
ECHO.%INFO%21.batch适配新菜单%RESET%
ECHO.%INFO%22.修改z10-dm刷写全自动%RESET%