ro.system.build.date=Fri Jan 23 22:33:51 CST 2026
ro.build.type=debug
ro.system.build.type=debug-key
ro.build.version=1.3.6 260123 Debug Test
ro.build.date.utc=1769178831
ro.product.current.softversion=1.3.6
ro.product.commit=b258b95
ro.system.build.tags=debug-key
ro.product.locale=zh-CN
ro.build.user=AHA
