ro.alltoolbox.build.date=Fri Jan 23 22:33:51 CST 2026
ro.build.type=debug
ro.build.version=1.4.0 260123 Debug Test
ro.build.date.utc=1769178831
ro.product.current.softversion=1.4.0
ro.product.commit=b258b95
persist.atb.xtc.allow=True
persist.xtc_allow_lock_True=True
